# -*- coding: utf-8 -*-
"""coursera_capstone

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LdbXN30lzukPt3waA_dcOkGjEET-SvUr

This is a sample markdown. This notebook will be used for the capstone project.
"""

import pandas as pd
import numpy as np

print("Hello Capstone Project Course!")